### ISSUE TITLE
Players list doesn't display: unable to select player

### ISSUE THREAD

**Issue by erikaburbach** [10up/brightcove-video-connect#72]
After adding a second Brightcove account, after switching from the default account and attempting to embed a video, the list of Players isn't available, I can only select the video/playlist and use the default player for the account.

If I switch the default account in settings, the problem then occurs with the previously default account.

Players did display one time in this scenario. After the first embed from the secondary account, the player list will not display again after several tests, and can reproduce the same problem after uninstall/reinstall of plugin.

Using the latest version of the plugin on Chrome/Mac.

Wordpress Version 4.6.1

**Comment by sudar** [comment]
@erikaburbach 

We are looking into this issue. Please provide us the following details, so that it will help us to debug this further.

Are there any other plugins that are installed? If yes, then can you give me the list of plugins that are listed?

Also when the players are not listed are there any JavaScript errors displayed in your browser?

**Comment by erikaburbach** [comment]
Thanks @sudar . I did a cleanup of the db, removed transients etc and seems to be working ok now. will ping back if it comes up again.  It's a test server, so not much else, no JS errors.
